"""base revision

Revision ID: 223804896c5a
Revises: 
Create Date: 2025-03-18 10:39:19.105120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '223804896c5a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_detail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('server_name', sa.String(length=250), nullable=False),
    sa.Column('api_name', sa.String(length=250), nullable=False),
    sa.Column('api_url', sa.String(length=250), nullable=False),
    sa.Column('auth_type', sa.String(length=250), nullable=False),
    sa.Column('http_method', sa.String(length=250), nullable=False),
    sa.Column('username', sa.String(length=250), nullable=True),
    sa.Column('password', sa.String(length=250), nullable=True),
    sa.Column('bearer_token', sa.String(length=250), nullable=True),
    sa.Column('auth_url', sa.String(length=250), nullable=True),
    sa.Column('client_id', sa.String(length=250), nullable=True),
    sa.Column('client_secret', sa.String(length=250), nullable=True),
    sa.Column('scope', sa.String(length=250), nullable=True),
    sa.Column('grant_type', sa.String(length=250), nullable=True),
    sa.Column('created_by', sa.String(length=250), nullable=True),
    sa.Column('modified_by', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_detail_id'), 'auth_detail', ['id'], unique=False)
    op.create_table('comcast',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hub_id', sa.String(length=250), nullable=False),
    sa.Column('partner', sa.String(length=250), nullable=False),
    sa.Column('hubCode', sa.String(length=250), nullable=False),
    sa.Column('hubName', sa.String(length=250), nullable=False),
    sa.Column('hubType', sa.String(length=250), nullable=False),
    sa.Column('primaryHubId', sa.String(length=250), nullable=False),
    sa.Column('addr1', sa.Text(), nullable=False),
    sa.Column('addr2', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=250), nullable=False),
    sa.Column('BuhmId', sa.String(length=250), nullable=False),
    sa.Column('countryCode', sa.String(length=250), nullable=False),
    sa.Column('locality', sa.String(length=250), nullable=False),
    sa.Column('serviceStatus', sa.String(length=250), nullable=False),
    sa.Column('state', sa.String(length=250), nullable=False),
    sa.Column('zipCode', sa.String(length=250), nullable=False),
    sa.Column('timezone', sa.String(length=250), nullable=False),
    sa.Column('location_type', sa.String(length=250), nullable=False),
    sa.Column('coordinates', sa.String(length=250), nullable=False),
    sa.Column('createdBy', sa.String(length=250), nullable=True),
    sa.Column('modifiedBy', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comcast_id'), 'comcast', ['id'], unique=False)
    op.create_table('mapping',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mapping_profile', sa.String(length=250), nullable=False),
    sa.Column('server_name', sa.String(length=250), nullable=False),
    sa.Column('rule', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.String(length=250), nullable=True),
    sa.Column('modified_by', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mapping_profile')
    )
    op.create_index(op.f('ix_mapping_id'), 'mapping', ['id'], unique=False)
    op.create_table('nlyte',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hub_id', sa.String(length=250), nullable=False),
    sa.Column('dc_id', sa.String(length=250), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.Column('latitude', sa.String(length=250), nullable=False),
    sa.Column('longitude', sa.String(length=250), nullable=False),
    sa.Column('power_capacity_kw', sa.Float(), nullable=False),
    sa.Column('available_power_capacity_kw', sa.Float(), nullable=False),
    sa.Column('total_racks', sa.Integer(), nullable=False),
    sa.Column('available_racks', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.String(length=250), nullable=False),
    sa.Column('asset_type', sa.String(length=250), nullable=False),
    sa.Column('manufacturer', sa.String(length=250), nullable=False),
    sa.Column('model', sa.String(length=250), nullable=False),
    sa.Column('asset_status', sa.String(length=250), nullable=False),
    sa.Column('asset_location', sa.String(length=250), nullable=False),
    sa.Column('power_consumption_kw', sa.Float(), nullable=False),
    sa.Column('peak_usage_kw', sa.Float(), nullable=False),
    sa.Column('average_usage_kw', sa.Float(), nullable=False),
    sa.Column('energy_efficiency_rating', sa.String(length=250), nullable=False),
    sa.Column('cooling_capacity_ton', sa.Float(), nullable=False),
    sa.Column('current_temperature_celsius', sa.Float(), nullable=False),
    sa.Column('cooling_unit_status', sa.String(length=250), nullable=False),
    sa.Column('cooling_unit_location', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nlyte_id'), 'nlyte', ['id'], unique=False)
    op.create_table('spatial',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hub_id', sa.String(length=250), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('region', sa.String(length=250), nullable=False),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.Column('latitude', sa.String(length=250), nullable=False),
    sa.Column('longitude', sa.String(length=250), nullable=False),
    sa.Column('power_capacity_kw', sa.Float(), nullable=False),
    sa.Column('cooling_capacity_ton', sa.Float(), nullable=False),
    sa.Column('infrastructure_type', sa.String(length=250), nullable=False),
    sa.Column('infrastructure_status', sa.String(length=250), nullable=False),
    sa.Column('infrastructure_capacity', sa.Integer(), nullable=True),
    sa.Column('propagation_distance_km', sa.Float(), nullable=False),
    sa.Column('terrain_type', sa.String(length=250), nullable=False),
    sa.Column('signal_loss_db', sa.Float(), nullable=False),
    sa.Column('interference_level_db', sa.Float(), nullable=True),
    sa.Column('coverage_area_km2', sa.Float(), nullable=False),
    sa.Column('signal_strength_dbm', sa.Float(), nullable=False),
    sa.Column('network_type', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spatial_id'), 'spatial', ['id'], unique=False)
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=250), nullable=False),
    sa.Column('hub_id', sa.String(length=250), nullable=False),
    sa.Column('order_status', sa.String(length=250), nullable=False),
    sa.Column('created_by', sa.String(length=250), nullable=True),
    sa.Column('modified_by', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_id'), 'transaction', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_id'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_spatial_id'), table_name='spatial')
    op.drop_table('spatial')
    op.drop_index(op.f('ix_nlyte_id'), table_name='nlyte')
    op.drop_table('nlyte')
    op.drop_index(op.f('ix_mapping_id'), table_name='mapping')
    op.drop_table('mapping')
    op.drop_index(op.f('ix_comcast_id'), table_name='comcast')
    op.drop_table('comcast')
    op.drop_index(op.f('ix_auth_detail_id'), table_name='auth_detail')
    op.drop_table('auth_detail')
    # ### end Alembic commands ###
