"""rel

Revision ID: b5542d0660ea
Revises: 223804896c5a
Create Date: 2025-03-18 22:30:04.546857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b5542d0660ea"
down_revision: Union[str, None] = "223804896c5a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("comcast", sa.Column("tid", sa.String(length=250), nullable=True))

    op.add_column("nlyte", sa.Column("tid", sa.String(length=250), nullable=True))

    op.add_column("spatial", sa.Column("tid", sa.String(length=250), nullable=True))

    op.add_column(
        "transaction", sa.Column("tid", sa.String(length=250), nullable=False)
    )
    op.create_unique_constraint(None, "transaction", ["tid"])
    op.drop_column("transaction", "order_id")
    op.drop_column("transaction", "hub_id")
    op.create_foreign_key(None, "comcast", "transaction", ["tid"], ["tid"])
    op.create_foreign_key(None, "nlyte", "transaction", ["tid"], ["tid"])
    op.create_foreign_key(None, "spatial", "transaction", ["tid"], ["tid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transaction",
        sa.Column(
            "hub_id", sa.VARCHAR(length=250), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "transaction",
        sa.Column(
            "order_id", sa.VARCHAR(length=250), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "transaction", type_="unique")
    op.drop_column("transaction", "tid")
    op.drop_constraint(None, "spatial", type_="foreignkey")
    op.drop_column("spatial", "tid")
    op.drop_constraint(None, "nlyte", type_="foreignkey")
    op.drop_column("nlyte", "tid")
    op.drop_constraint(None, "comcast", type_="foreignkey")
    op.drop_column("comcast", "tid")
    # ### end Alembic commands ###
