"""create hub vs buhm table

Revision ID: c39031556e8f
Revises: 28e1893366d4
Create Date: 2025-03-20 08:44:57.059981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c39031556e8f'
down_revision: Union[str, None] = '28e1893366d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hub_vs_buhm',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hub_id', sa.String(length=250), nullable=False),
    sa.Column('BuhmId', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hub_vs_buhm_id'), 'hub_vs_buhm', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hub_vs_buhm_id'), table_name='hub_vs_buhm')
    op.drop_table('hub_vs_buhm')
    # ### end Alembic commands ###
